# vim: ts=2 sw=2 et :
---
language: python

sudo: required

install:
  - pip install -r requirements.txt

script:
  - pytest

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
